### ISSUE TITLE
Include installed packages in the debug command

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt#1236]
### Feature description
Include installed packages in the `debug` command.
Something like:
```
Packages:
  dbt_utils==0.1.21
  segment==0.1.4
```

### Who will this benefit?
Users that install packages via hub that don't use a strict equality – this will help them with version resolution.

### Other things to think about
- Should we indicate how the package was installed? i.e. local vs. git vs. hub?

**Comment by sungchun12** [comment]
Should this issue be closed since this versioning is built into `dbt deps`?

**Comment by jtcohen6** [comment]
@sungchun12 I think so! Let's consider this resolved by #3759 :)

**Comment by sungchun12** [comment]
I linked the pull request :)
