### ISSUE TITLE
Split out hooks and seeds from ParsedNodes

### ISSUE THREAD

**Issue by beckjake** [dbt-labs/dbt#1601]
## Feature
Split hooks/seeds out of ParsedNodes

### Feature description
In #1589, I split `ParsedTestNode` contracts out from `ParsedNode` contracts. We should split hooks out ( to give them `index` and remove it from `ParsedNode`) and maybe also seeds/analyses for consistency.

### Who will this benefit?
developers: Won't need to drag weird hook data around for non-hook nodes, also this makes it easier to add resource-type-specific data and methods in the future.

**Comment by jtcohen6** [comment]
This is an oldie. The thrust of it remains true, but is better captured in #3557
