### ISSUE TITLE
Improve the query status in stdout for pg/redshift

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt#1889]
### Describe the feature
Presently, the status returned by Postgres/Redshift is something like `INSERT 0 1234` for incremental models. Instead, we should parse out the number of rows affected and render this as the status:
```
... [Insert 1200 in 34.2s]
```

We already do some status parsing on Snowflake + BigQuery, and it would make sense to apply similar logic to Pg/Redshift too.

Bonus points: incremental models run a `delete` and `insert` on pg/Redshift - can we capture the output of each of these statements and render them in the status like?

```
....[Update 10, Insert 1190 in 34.2s]
```

^ This second version might be tricky, and I'm ok with not supporting it at the present time.

**Comment by jtcohen6** [comment]
I'm going to consider this resolved, for now, by the addition of `adapter_response.rows_affected` in `run_results.json`, which is the most reliable way to access this metadata. That said, I agree that:
- It's a bit weird that we display `INSERT 0 X` as the CLI status
- I'd _love_ to include both numbers of affected rows, for incremental upserts that perform `delete` + `insert`
