### ISSUE TITLE
Run integration tests on macos

### ISSUE THREAD

**Issue by beckjake** [dbt-labs/dbt#1949]
### Describe the feature
We should run integration tests on macos for CI

### Describe alternatives you've considered
- Get everyone to run the integration suite locally on their laptops
- Continue not testing macos
- Let our users find the bugs first

### Additional context
We currently run tests for linux and windows before merging dbt pull requests, including tests that exercise `pip install` for dbt and then run dbt.

We should run those tests on macos as part of our CI process. In particular, we care that the various packages would install via a `pip install dbt` and successfully run if the current commit were released. 

This is becoming more significant as we deal with the intersection of version changes between operating systems, `python`, `pip`, and various dependencies (especially `psycopg2`). It would be good to at least have a baseline of tests against the latest macos version.

### Who will this benefit?
End users on macos who don't have to be the ones to find out that `pip install dbt` doesn't work
Developers who can now merge minor dependency changes with slightly less fear

**Comment by leahwicz** [comment]
Adding mac to the integration CI test: https://github.com/fishtown-analytics/dbt/pull/3396
