### ISSUE TITLE
Warnings in Python 3.8 regarding incompatibility

### ISSUE THREAD

**Issue by tirkarthi** [dbt-labs/dbt#2342]
### Describe the bug

* Deprecation warnings due to invalid escape sequences.
* Imporing ABC directly from collections was deprecated and will be removed in Python 3.10

### Steps To Reproduce

Deprecation warnings

```
find . -iname '*py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./test/unit/test_postgres_adapter.py:194: DeprecationWarning: invalid escape sequence \ 
  options="-c search_path=test\ test")
./test/unit/test_query_headers.py:37: DeprecationWarning: invalid escape sequence \/
  self.assertTrue(re.match(f'^\/\*.*\*\/\n{self.query}$', sql))
```

Potential incompatible imports

```
rg -t py 'time.clock|base64.encodestring|base64.decodestring|etree.celementtree|collections\.(Awaitable|Coroutine|AsyncIterable|AsyncIterator|AsyncGenerator|Hashable|Iterable|Iterator|Generator|Reversible|Sized|Container|Callable|Collection|Set|MutableSet|Mapping|MutableMapping|MappingView|KeysView|ItemsView|ValuesView|Sequence|MutableSequence|ByteString)|asyncio\.coroutine'
core/dbt/utils.py
295:        if not isinstance(args, collections.Hashable):
```

### System information

**The operating system you're using:** Linux

**The output of `python --version`:** 3.8

**Comment by tirkarthi** [comment]
I will add a PR for this.

**Comment by drewbanin** [comment]
Thanks for opening this issue - a PR would be very welcomed!

**Comment by tirkarthi** [comment]
Unfortunately, I will not be able to work on it for sometime. I will leave it to others. This should be an easy task for new contributors. Thanks.

**Comment by jtcohen6** [comment]
I believe this was resolved by https://github.com/dbt-labs/dbt/pull/2357 [here](https://github.com/dbt-labs/dbt/commit/c69f28e0a09e27bd8581cdcef7aec49e5562749b#diff-3113975fdb70cadc0c7b5f58d67b41fb50b7819a848b8244bb50d32e959d9f7fR292)
