### ISSUE TITLE
Ability to run snapshot-freshness with tag selection

### ISSUE THREAD

**Issue by nehiljain** [dbt-labs/dbt#2369]
### Describe the feature
Allow dbt users to run `dbt source snapshot-freshness --select tag:mytag`

DBT already has the ability to do this for models but would love to do this for sources as well. 
Business Context: 

### Describe alternatives you've considered

- Run the whole tree and not use tag selection

### Who will this benefit?
Anyone who has dbt monorepo used by multiple teams. They can run trees inside dbt owned by different teams. These trees are tagged by team name so its as easy as `dbt run -m tag:teamname`, `dbt test -m tag:teamname` etc.

**Comment by drewbanin** [comment]
Thanks for opening this issue @nehiljain! If you (or anyone else) is interested in working on this, I think it should be a pretty isolated change :)

**Comment by nehiljain** [comment]
Yeah, I will take a crack at it. Do you want to point me to the relevant code files?

**Comment by beckjake** [comment]
Hi @nehiljain, I think you'll want to change `core/dbt/task/freshness.py`, in particular the `build_query` method's `include` value.

**Comment by nehiljain** [comment]
Is tagging supported at the source level? I was not able to see tags key on the sources in my manifest.json

Example: 
![snowflake_spend_manifest;.json](https://p91.f3.n0.cdn.getcloudapp.com/items/o0ugP1ZP/Image%202020-05-02%20at%2010.26.37%20pm.png?v=99fb2d5c24e4fcb75e7f7d5953f4aa10)

**Comment by drewbanin** [comment]
hmm @nehiljain I do think I see the `tags` property on ParsedSnapshotNodes -- check out `core/dbt/contracts/graph/parsed.py`. My instinct is that the tags property is present on the Snapshot objects, but it's not being serialized to the manifest. Does that sound possible @beckjake?

**Comment by beckjake** [comment]
@nehiljain Is it possible you're on dbt 0.15.x? Tags were added to the ParsedSourceDefinition object in 0.16.0.

In 0.17.x we seem to have regressed - tags appear to be getting clobbered by the new source-patching code. I'm surprised and annoyed to find that we apparently have no tests for this.

**Comment by jtcohen6** [comment]
Closing in favor of #2987, to be resolved by #3554
