### ISSUE TITLE
Enact deprecations

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#2798]
### Describe the feature

- As of dbt v0.18.0, we collect anonymous usage stats for deprecation warnings.
- We were already planning to end support for `config-version: 1` of `dbt_project.yml` in dbt v0.19.0 (per implementation of #2735)
- We should officially deprecate:
    - `dbt-project-yaml-1`: this is far & away the most common deprecation warning, and we still see it popping up in ~40% of projects running v0.18.0. Users may have upgraded their own projects but still need to upgrade installed packages. In any case, this is definitely the most controversial of our proposed deprecations.
    - `column-quoting-unset`: 11% of projects
    - `models-key-mismatch`: 2% of projects
    - `materialization-return`: <1% of projects
    - `not-a-dictionary`: 0% of projects
- We should _not_ deprecate:
    - `adapter-macro`: this is the second-most-common deprecation warning, and we only introduced it in v0.18 with the switch to `adapter.dispatch`. We should give users at least one more minor version to upgrade.

### Describe alternatives you've considered
- Leaving these as warnings until v1.0.0, or forever

### Who will this benefit?
- Us as dbt maintainers in the short term, as we can reduce the surface area of code that patched older syntaxes
- Users, in the long run, as we continue to crystallize the UX of dbt project development

**Comment by jtcohen6** [comment]
Note: dbt v0.19.0 did deprecate `dbt-project-yaml-1`, in exchange for improved `state:modified` behavior around env-based configs (#2735).

It's one of the few times that we've entirely removed a piece of functionality—definitions of `vars` that are different for different model subdirectories—without replacing it, or rearchitecting it, in a way that achieved functional parity. The original behavior was an accident of the initial `vars` implementation, and the current implementation (project-level `vars`) is much easier to manage and rationalize. Despite not being a feature we had really documented or encouraged, folks did leverage it for certain use cases, and now they can't.

This is something we'll want to keep thinking about, and develop rigorous communication plans, ahead of releasing v1.0.

**Comment by jtcohen6** [comment]
There's at least one new deprecation since we opened this ticket:
- `dispatch-packages`

We should establish a consistent habit around deprecations, with a few options:
- never removing functionality / always maintaining backwards compatibility
- removing deprecated functionality only in major versions

**Comment by leahwicz** [comment]
@jtcohen6 would the goal be to add these deprecation warnings to `0.21.0` and then actually remove the functionality in `1.0`? 

Also is this the official list? I want to track what we need to do for sure. I might try picking some of these up or having Emily pick this up...

- [ ] dbt-project-yaml-1
- [ ] column-quoting-unset
- [ ] models-key-mismatch
- [ ] materialization-return
- [ ] not-a-dictionary
- [ ] dispatch-packages

**Comment by jtcohen6** [comment]
This issue can really be split up into a bunch of smaller tasks, each one targeting one of the active deprecation warnings that we currently have in place. I can do my best to provide pointers for each. I'll include a few below, and add more when I have more time.

### dispatch-packages

Instead of raising a deprecation warning when the user has defined the `packages` arg, or has passed a list instead of a string, we should instead raise a clear error. That error message should point to the same documentation that the [deprecation warning message](https://github.com/dbt-labs/dbt/blob/9d7a6556efb9bdbbfedf24b6f01ded90595a572d/core/dbt/deprecations.py#L46-L57) currently does 

https://github.com/dbt-labs/dbt/blob/96083dcaf51ab7725f1b554891581e1522e32d7d/core/dbt/context/providers.py#L137-L140

Then, we can:
- Remove `DispatchPackagesDeprecation` from the list of active deprecations
- Significantly simplify the logic (removing jank backwards compatibility) from [`jinja_static.py`](https://github.com/dbt-labs/dbt/blob/develop/core/dbt/clients/jinja_static.py) — to discuss with @gshank 

### materialization-return

https://github.com/dbt-labs/dbt/blob/96083dcaf51ab7725f1b554891581e1522e32d7d/core/dbt/task/run.py#L208-L225

- Remove the conditional branch `if isinstance(result, str)` that raises a deprecation warning and handles the string `result`. If `result` isn't a dictionary that passes `_validate_materialization_relations_dict`, we should just raise an exception.
- Remove `MaterializationReturnDeprecation` from the list of active deprecations

(will keep adding to this comment later)

**Comment by emmyoop** [comment]
Opened [#415](https://github.com/dbt-labs/dbt-utils/issues/415) in dbt-utils because of newly introduced use of packages.  Will need to be resolved before enacting deprecation for dispatch-packages.

**Comment by emmyoop** [comment]
All deprecations listed above have been merged into develop.  Closing.

**Comment by jtcohen6** [comment]
woohoo !!
