### ISSUE TITLE
POSTGRES Incremental Load Query 

### ISSUE THREAD

**Issue by rajeshmese** [dbt-labs/dbt#3020]
Currently DBT generates Delete + Update queries for Incremental Load. Is there any way  changing it to INSERT ON CONFLICT DO UPDATE queries or any other efficient way to do Upsert for more than 10 million rows.

**Comment by jtcohen6** [comment]
Hey @rajeshmese, could you say a bit more about the benefits of `INSERT ON CONFLICT DO UPDATE`, or the specific problems you're running into?

This is something you could accomplish in your own project by overriding the [`incremental_upsert`](https://github.com/fishtown-analytics/dbt/blob/a34a8777374259ba90c11765ca69001b4d75040f/core/dbt/include/global_project/macros/materializations/incremental/helpers.sql#L2-L20) macro, i.e. adding a macro by that name to a file in your project's `macros/` folder, and editing it to include the `on conflict` logic you need.

I'd be interested to hear if this is a change we should make for all incremental models when running on postgres.

**Comment by rajeshmese** [comment]
This is required because we have to maintain separate timestamp columns for Insert and Update time. Since DBT making DELETE+Insert it is not possible to do capture  update timestamp.

**Comment by jtcohen6** [comment]
> @jtcohen6 This is required because we have to maintain separate timestamp columns for Insert and Update time. Since DBT making DELETE+Insert it is not possible to do capture update timestamp.

I'm pretty sure you can get what you're after by adding a `current_timestamp` column to your model SQL. The `delete+insert` incremental model accomplishes "updates" by deleting an old record, and inserting the new one, if they match on the `unique_id`. In that sense, the insert timestamp _is the same as_ the update timestamp you're after. Or am I misunderstanding?

**Comment by rajeshmese** [comment]
@jtcohen6 yes.

**Comment by jtcohen6** [comment]
Going to close this, as it seems we reached a resolution several months ago without requiring a core or adapter code change. Feel free to comment if you disagree
