### ISSUE TITLE
Incremental compiling / auto-build

### ISSUE THREAD

**Issue by ruisun-pep** [dbt-labs/dbt#3121]
### Describe the feature

There has been plenty of discussion on how to making the rendering / parsing process faster and here is an idea I have been contemplating. 

Create a long-running dbt process (`dbt build-server`) that:

1. At start, build the project from scratch
2. After that, monitor files within project and rebuild that file whenever there is a change (update graph, compile SQL)
3. `dbt run` and other commands will use the already compile sql.

Similar mechanisms are implemented in various projects. Django (and many other web frameworks) development server supports [live reload](https://docs.djangoproject.com/en/3.1/ref/django-admin/#runserver); IntelliJ supports [auto & incremental build](https://www.jetbrains.com/help/idea/compiling-applications.html#auto-build) of Java classes on each file change.

### Describe alternatives you've considered

Currently, dbt will rebuild the whole project whenever we execute `dbt run`. This is very inefficient because most of the time the changes are limited to a few models only.

### Additional context

This feature is not database specific.

### Who will this benefit?

Everyone who develop with dbt extensively.

### Are you interested in contributing this feature?

Yes

**Comment by jtcohen6** [comment]
Hey @ruisun-pep, check out the **dbt RPC server** [docs](https://docs.getdbt.com/reference/commands/rpc/)! I think this may be exactly what you have in mind.

In particular, the section on [reloading the server](https://docs.getdbt.com/reference/commands/rpc/#reloading-the-server):

> When the dbt Server starts, it will load the dbt project into memory using the files present on disk at startup. If the files in the dbt project should change (either during development or in a deployment), the dbt Server can be updated live without cycling the server process. To reload the files present on disk, send a "hangup" signal to the running server process using the Process ID (pid) of the running process.

Coupled with [partial parsing](https://docs.getdbt.com/reference/profiles.yml/#partial_parse):

> If partial parsing is enabled and files are unchanged between invocations of dbt, then dbt does not need to re-parse these files — it can instead use the parsed representation from the last invocation of dbt. If a file has changed between invocations of dbt, then dbt will re-parse the file and update the parsed node cache accordingly.

There's one specific difference worth calling out: dbt builds the DAG at project parse time, whereas it compiles Jinja-SQL templates at node compilation/execution time. The RPC server and partial parsing manage to skip the first, but there's no getting around the latter—which is okay, since that compilation time is more evenly spread across the execution of each model/test/seed/snapshot/etc.

**Comment by ruisun-pep** [comment]
Hey @jtcohen6 , thanks for sharing about rpc server and partial parsing! From my experiment with dbt's rpc server, issuing a `run` command seems to be faster than issuing the equivalent of a `cli_args` command. So my question is, what happens when:

1. The rpc server loads (and reloads) the project, besides building the DAG?
2. RPC server executes a run command?
3. RPC server executes a cli_args command?

**Comment by jtcohen6** [comment]
1. At RPC server startup, dbt loads files, creates parsed (Python) representations of the objects in them, compiles Jinja templates as necessary to capture source/ref calls and render config values, constructs a manifest, and then queries database metadata to build the runtime cache. It's all the things that are slow today at dbt project startup, and which I wrote a bit about [on discourse here](https://discourse.getdbt.com/t/faster-dbt-startup-in-v0-19-1-beta/2142). When issued a "hangup" signal, indicating that files in the project have changed, the server will repeat the entire process, _unless_ partial parsing is enabled, in which case it will skip some of the earlier steps for unchanged files.

If you send the RPC server a request too early, or while it's recompiling the project, you'll receive an error like:
```json
{
    "error": {
        "code": 10010,
        "message": "RPC server is compiling the project, call the \"status\" method for compile status",
        "data": {
            "type": "RPCCompiling",
            "message": "Runtime Error\n  compile in progress",
            "tags": null
        }
    },
    "id": "2db9a2fe-9a39-41ef-828c-25e04dd6b07d",
    "jsonrpc": "2.0"
}
```

The CLI analog for these steps is the time between issuing the command and seeing the first model start running. These designations are not exact, but each roughly corresponds to the most time-intensive thing dbt is doing:
```
12:05:40 ~/... $ dbt run
Running with dbt=0.19.0
<-- project startup -->
Found 217 models, 302 tests, 3 snapshots, 1 analysis, 364 macros, 1 operation, 13 seed files, 67 sources, 4 exposures
<-- building cache -->
12:06:15 | Concurrency: 8 threads (target='dev')
12:06:15 |
12:06:15 | 1 of 212 START view model dbt_jcohen.my_first_model... [RUN]
```

2. The `run` method takes as its starting point the manifest (parsed representation of the project) built by step 1. It still needs to query adapter metadata and build the runtime cache, but it manages to skip nearly all of parsing, instead jumping right into SQL compilation and execution the `run` task for some/every model. You could think of it as jumping straight to the `Found 217 models` line, whereas it takes the CLI 

3. The `cli_args` command is slower for a very simple reason: It needs to be able to do anything a CLI invocation can do, namely accept override values passed to `--vars` on the command/method. It doesn't get to jump straight to "Found" in the same way. (https://github.com/fishtown-analytics/dbt/issues/2265 and https://github.com/fishtown-analytics/dbt/pull/2363 for some history on this; https://github.com/fishtown-analytics/dbt/issues/3126 for how this behavior is still imperfectly consistent.)

Just anecdotal, here are some comparison times from two local RPC requests in a medium-sized project with dbt v0.19.0. Both requests are performing the same function—running one model—once by the dedicated `run` method, and once by the flexible `cli_args` method. In neither case am I using partial parsing.

| Timestamp        | What just finished?  | run      | (elapsed) | cli_args | (elapsed) |
|------------------|----------------------|----------|-----------|----------|-----------|
| Start invocation |                      | 11:09:20 |           | 11:19:30 |           |
| First log line   | Interpreting request | 11:09:24 |   0:00:05 | 11:19:35 |   0:00:04 |
| "Found..."       | Parsing project      | 11:09:24 |   0:00:00 | 11:19:55 |   0:00:21 |
| Begin model      | Runtime cache        | 11:09:38 |   0:00:13 | 11:20:05 |   0:00:10 |
| End invocation   | Materializing model, etc            | 11:09:51 |   0:00:13 | 11:20:20 |   0:00:15 |

The primary difference is the 21 seconds in which `cli_args` re-parses project files and constructs a manifest. Here's the same, but using dbt v0.19.1-b2 (which has ~2-3x faster project parse time):

| Timestamp        | What just finished?  | run      | (elapsed) | cli_args | (elapsed) |
|------------------|----------------------|----------|-----------|----------|-----------|
| Start invocation |                      | 11:47:14 |           | 11:50:48 |           |
| First log line   | Interpreting request | 11:47:20 |   0:00:06 | 11:50:54 |   0:00:06 |
| "Found..."       | Parsing project      | 11:47:20 |   0:00:00 | 11:51:02 |   0:00:07 |
| Begin model      | Runtime cache        | 11:47:30 |   0:00:11 | 11:51:14 |   0:00:12 |
| End invocation   | Materializing model, etc            | 11:47:42 |   0:00:12 | 11:51:32 |   0:00:18 |
