### ISSUE TITLE
Scrub environment variables in target + logs

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3440]
### Describe the feature

Could we scrub environment variables (values templated by `env_var`) from `target/` and `logs/`?

We could consider doing this for:
- All environment variables
- Environment variables prefixed with `SECRET_`

I don't have a great sense of what would be involved here. The best approach would tie into each actual `env_var` call. A less-good approach would grep strings for env vars before writing to files.

### Describe alternatives you've considered

The primary motivation for this request is dbt Cloud. dbt Core feels like the best place to handle it, however, and many Core users have asked for it ([e.g.](https://github.com/fishtown-analytics/dbt-spark/issues/147#issuecomment-843627607)).

### Additional context

- Not specific to any database
- Scrubbing environment variables from JSON artifacts also scrubs them in dbt-docs

### Who will this benefit?

- More complex, security-conscious deployments

**Comment by jtcohen6** [comment]
@drewbanin Tagged as requested! Would love to hear your thoughts here, as it sounds like we've done something similar with logbook before.

**Comment by drewbanin** [comment]
@jtcohen6 I am not 100% sure of the canonical way to do this, but I think that we can add a log processor to the logbook LogManager

This is where we set up different log handlers (they emit logs) and log processors (they modify log lines). See some examples [here](https://logbook.readthedocs.io/en/stable/setups.html#deeply-nested-setups)

So, we'd add a new processor around here:
https://github.com/dbt-labs/dbt/blob/b9d5123aa37786425f7429c91f4513839eea6a65/core/dbt/logger.py#L467-L486

And that processor could look something like:
```
class ScrubProcessor(logbook.Processor):
    def process(self, record):
        record.message = record.message.replace("dbt", "♡")
```

Think we'll have some work to do to capture relevant environment variables for scrubbing, but if we do it this way, all log output (whether to stdout, stderr, json/text formatting, written to a file) should be scrubbed of specified secrets :)

**Comment by jtcohen6** [comment]
@drewbanin Thanks for the pointers! That approach seems eminently doable, I just tried it locally and had some success:

```python
SECRET_ENV_PREFIX = 'DBT_ENV_SECRET_'

def get_metadata_env() -> List[str]:
    return [
        v for k, v in os.environ.items()
        if k.startswith(SECRET_ENV_PREFIX)
    ]

class ScrubProcessor(logbook.Processor):
    def process(self, record):
        for secret in get_metadata_env():
            record.message = record.message.replace(secret, "♡" * len(secret))
```
```
Completed with 2 errors and 0 warnings:

Database Error in model view_1 (models/view_1.sql)
  relation "♡♡♡♡♡♡♡♡♡♡♡.table1" does not exist
  LINE 10: FROM ♡♡♡♡♡♡♡♡♡♡♡.table1
                ^
  compiled SQL at target/run/my_project/models/view_1.sql

Database Error in model view_2 (models/view_2.sql)
  relation "♡♡♡♡♡♡♡♡♡♡♡.table2" does not exist
  LINE 14: FROM ♡♡♡♡♡♡♡♡♡♡♡.table2
                ^
  compiled SQL at target/run/my_project/models/view_2.sql
``` 

Worth noting that this won't scrub env var output in dbt artifacts (`manifest.json`, `run_results.json`), but that doesn't tend to be the most sensitive information. At that point, something is being written to documentation or the database. We're much more interested in use cases like:
- Git access tokens for `dbt deps`
- Cloud storage secrets, e.g. for reading external data

**Comment by drewbanin** [comment]
cool! Just want to be clear about this - I have no problem at all with using a ❤️ in these log lines. It's 2021, apps should support unicode & I think Snowflake used to use smiley faces :p

I think that if you're compiling env vars into a model (or similar) then it's reasonable to see their unredacted versions in the build artifacts. I could buy an argument for scrubbing them, but don't know that it needs to happen in the v1 of this thing.
