### ISSUE TITLE
Add experimental parser correctness checks to tracking

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt#3503]
### Describe the feature
`1 / n` parses with the experimental parser should run both python jinja parsing and the experimental parser, compare results and send back whether they match or not. Frequency should be determined with an rng.

### Describe alternatives you've considered
Not having this information

### Additional context
We want to make sure the experimental parser is 100% in line with the existing python jinja rendering before we consider turning it on by default. 

### Who will this benefit?
dbt maintainers

### Relevant Tickets
#3438

**Comment by jtcohen6** [comment]
@nathaniel-may How do we want to account for known edge cases? For instance, we _know_ that the experimental parser will not work right if the user has implemented custom versions of the `ref`, `source`, or `config` macros

**Comment by nathaniel-may** [comment]
for now those will fail. However, once those edge cases are accounted for they won't. And we'd want to see an RC with zero of these failures before moving to turn it on by default. So in my opinion it's ok to include this before we have all the edge cases covered.
