### ISSUE TITLE
The rpc server returns incorrect results when queries contain duplicate column names

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt#3527]
### Describe the bug
The rpc server returns incorrect results when queries contain duplicate column names. The rpc server does correctly alias duplicate columns and adds a suffix (eg. `column_name_2`), but the contents of the values for that column are `null` in the rpc response!

### Steps To Reproduce
1. start the rpc server
2. execute a query like `select 1 as id, 2 as id`
3. Observe that the `id_2` column contains a `null` value instead of the value "2"

### Expected behavior
- The duplicated columns may be suffixed with an integer
- The contents of that column should reflect the values returned by the database rather than `null`

### Screenshots and log output
Example:
![image](https://user-images.githubusercontent.com/1541139/124154417-78e7b280-da63-11eb-9a9f-0be76e63278c.png)

### System information
Observed on dbt v0.20.0-rc1, should be database independent

**The output of `dbt --version`:**
```
0.20.0-rc1
```

### Additional context
I tried to determine if this is rpc-only or if it affects all queries:

```
{% macro test()  %}

    {% set sql %}
        select 1 id, 2 as id
    {% endset %}
    {% set res = run_query(sql) %}
    {% do res.print_table() %}

{% endmacro %}
```

When run with `dbt run-operation test` I do see:
```
❯ dbt run-operation test
Running with dbt=0.20.0-rc1
| ID | ID_2 |
| -- | ---- |
|  1 |    2 |
```

which makes me think that this is an rpc-only class of error!

**Comment by jtcohen6** [comment]
Oh no! We initially had this open in https://github.com/dbt-labs/dbt/issues/2625 + https://github.com/dbt-labs/dbt/issues/3147, and I thought it was fixed by https://github.com/dbt-labs/dbt/pull/3158, which should be included in v0.20.0-rc1.

I'll look into this later today to see if it's a different issue, or if the fix in #3158 was incomplete.

**Comment by jtcohen6** [comment]
@drewbanin I get the expected results when reproducing this with `dbt rpc` locally (using 0.20.0-rc2):

```
"results": [
    {
        "raw_sql": "select 1 as id, 2 as id",
        "compiled_sql": "select 1 as id, 2 as id",
        "table": {
            "column_names": [
                "id",
                "id_2"
            ],
            "rows": [
                [
                    1.0,
                    2.0
                ]
            ]
        },
    }
],
```

And in the dbt Cloud IDE (using `0.20.0-rc1`):

![Screen Shot 2021-07-01 at 5 06 08 PM](https://user-images.githubusercontent.com/13897643/124189402-a5fd8a80-da8e-11eb-8af2-06c7fe6951ce.png)

**Comment by drewbanin** [comment]
@jtcohen6 I am _so_ sorry for the false alarm!! You know, I was surprised when my run-operation test didn't fail in the way that I expected, and I actually did stop short of testing against the rpc server locally. Glad to hear it's already fixed, terribly sorry for the confusion - thanks for the pointer! Closing
