### ISSUE TITLE
Enable MFA token caching for Snowflake

### ISSUE THREAD

**Issue by mroy-seedbox** [dbt-labs/dbt#3539]
### Describe the feature
Snowflake supports MFA token caching, but it requires `snowflake-connector-python` version >= `2.3.7`: [link](https://docs.snowflake.com/en/user-guide/security-mfa.html#using-mfa-token-caching-to-minimize-the-number-of-prompts-during-authentication-optional).

MFA token caching allows to run DBT with accounts that have MFA enabled - without receiving an MFA/DUO push every single time DBT is run.

The only change that is required here is for DBT to bump the `snowflake-connector-python` to a version >= `2.3.7`.

### Describe alternatives you've considered
Not using accounts with MFA enabled for DBT. This requires the creation of separate accounts with MFA disabled, which is needless overhead. With this features, those secondary accounts could be deleted.

### Additional context
Snowflake only.

### Who will this benefit?
People who want to leverage the security benefits of using MFA.

### Are you interested in contributing this feature?
No

**Comment by jtcohen6** [comment]
@mroy-seedbox Right on! The next version of dbt (v0.20) will bump the dependency on `snowflake-connector-python` to `~=2.4.1`:

https://github.com/dbt-labs/dbt/blob/49065158f59f12c1040077735f891d2add4a8ee5/plugins/snowflake/setup.py#L48-L53

There's a [release candidate available now](https://discourse.getdbt.com/t/prerelease-v0-20-0-margaret-mead/2621), and we're planning to cut the final release very soon.
