### ISSUE TITLE
Skip yaml validation for files that are completely unchanged

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3563]
Thanks to https://github.com/dbt-labs/dbt/pull/3460, when dbt reads yaml files, it also performs minimal validation and stores their intermediate representation in dictionary form. This enables us to:
- Return good error messages early & often
- Better separate file loading from manifest construction
- In partial parsing: only re-parse nodes affected by specific lines changed in yaml files, rather than re-parsing all resources implicated in the entire yaml file

At the same time, partial parsing runs need to read and validate every yaml file in the project, every time. This should still be _really_ fast, even for big projects, so long as the user has `libyaml` installed (C bindings for `PyYAML`). I'm going to make sure we document this.

Would it be possible to have the best of both worlds, by storing a hash of the yaml file, and skip re-reading / validating it entirely if it's completely unchanged?

**Comment by jtcohen6** [comment]
@gshank would love to talk more about this when you're back next week!

**Comment by gshank** [comment]
We do store a yaml dictionary now (and the checksum), but those are in the partial parse msgpack file, and we have no access to it when the files are read. And it's only available when partial parsing is turned on. We could move that validation to the partial parsing code, but that does mean that the error messages are different from the messages issued by the schema parser. We could add that same minimal validation to the schema parser too, so that the errors are different. I do think that eventually we're going to want to have validation that's not derived from hologram, since those error messages are sometimes cryptic and hard to decipher. So we could consider that a first step in that direction.

**Comment by jtcohen6** [comment]
@gshank Thanks for weighing in! I was curious if there was a quick win here that could prevent the need to re-read + re-validate thousands of yaml files if zero files have been edited. It sounds like this would be a slightly bigger lift.

At the same time, we also believe that, so long as the user/deployment environment has optimized libraries installed, re-reading + re-validating thousands of yaml files should be very, very fast. Does that sound right? 

(cc @drewbanin)

**Comment by jtcohen6** [comment]
I spent some time today diving into the raw load-time data a bit more, and I'm seeing that in parsing steps where partial parsing "works" (`parsed_path_count < path_count`), the `read_files` step comprises a _huge_ portion of the total load time, **between 80-90%**. File reading by itself can take 2-7 ms per file. In very large projects, this feels like _the big thing_ standing between our pretty-darn-good v0.20 numbers (3-9 ms/path with partial parsing), versus our end-of-2021 goal of 1 ms / file, <5 s total in a 5k file project.

It feels like some reasonable next steps could be:
- Add tracking for whether users have the optimized `libyaml` installed, to validate whether this is a crucial differentiator. Ensure that dbt Cloud _is_ using the optimized C yaml bindings (cc @leahwicz)
- Following the proposal in this issue, store file hashes in `partial_parse.msgpack` and use that as a shortcut for file reading, even if it means some light refactoring and separation/duplication of validation steps

**Comment by drewbanin** [comment]
big +1 here - totally non-scientific but I also dug into the partial parsing perf data and found this same thing - dbt is doing a lot of (slow) work to determine that two .yml files are identical :)

**Comment by leahwicz** [comment]
@kwigley opened https://github.com/dbt-labs/dbt-cloud/pull/4018 to get the optimized`libyaml` into Cloud

I opened this issue to get the tracking work done as well: https://github.com/dbt-labs/dbt/issues/3845

**Comment by gshank** [comment]
In order to skip loading the files we'd need to look at the file timestamp instead of the checksum, because we can't get the checksums without reading the files. Is this something that we're comfortable doing?
