### ISSUE TITLE
Full-commented-out yaml file contents return ugly error

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3568]
### Describe the bug

A user reports seeing this error when trying to parse their project after upgrading to v0.20.0:
```
Encountered an error:
argument of type 'NoneType' is not iterable
```

This is the stacktrace:
```
File "/usr/local/Cellar/dbt/0.20.0_1/libexec/lib/python3.8/site-packages/dbt/parser/schemas.py", line 560, in check_format_version
    if 'version' not in yaml_dct:
TypeError: argument of type 'NoneType' is not iterable
```

That's very surprising! The error cropping up in this line:
https://github.com/dbt-labs/dbt/blob/f460d275baa4df8cf8713f27e198a3577d6ea71c/core/dbt/parser/schemas.py#L560

Means that `yaml_dct` must be set to `None`, somehow. That method is called here:
https://github.com/dbt-labs/dbt/blob/f460d275baa4df8cf8713f27e198a3577d6ea71c/core/dbt/parser/read_files.py#L21-L23

It's pretty hard to imagine [`yaml_from_file`](https://github.com/dbt-labs/dbt/blob/f460d275baa4df8cf8713f27e198a3577d6ea71c/core/dbt/parser/schemas.py#L99) returning `None`. I've tried a couple different things to trip this error (an empty `.yml` file, malformed contents, simply the word `'None'`), but none (hah) of my attemps has worked. The only way I've managed to reproduce it is by stepping directly into the `validate_yaml` or `yaml_from_file` method calls and setting the yaml dictionary to `None`.

One important hint: The user reports that this project runs fine on earlier versions of dbt. It's only with the upgrade to v0.20.0 that they started seeing this error.

### Steps To Reproduce
???

### Expected behavior
Definitely not this error!

**The output of `dbt --version`:**
```
/usr/local/Cellar/dbt/0.20.0_1/
```
(i.e. dbt v0.20.0 installed via Homebrew)

**Comment by nathaniel-may** [comment]
I wanted to take a quick peek at this, and drilling all the way down to our call to the [yaml loader](https://github.com/dbt-labs/dbt/blob/f460d275baa4df8cf8713f27e198a3577d6ea71c/core/dbt/clients/yaml_helper.py#L60), and we aren't passing along any `None` values in dbt. Looking at the [PyYaml documentation](https://pyyaml.org/wiki/PyYAMLDocumentation), this line stands out: "If there are no documents in the stream, it returns None." This, of course, is still very odd.

**Comment by jtcohen6** [comment]
### reproduction case

Create a yaml file that's all comments:
```yml
# models/schema.yml
# only comments here
```

Try parsing the project:
```
$ dbt --no-partial-parse parse
Running with dbt=0.20.0
14:19:08 | Start parsing.
14:19:08 | Dependencies loaded
14:19:08 | ManifestLoader created
Encountered an error:
argument of type 'NoneType' is not iterable
```

**Comment by leahwicz** [comment]
@nathaniel-may I'm assigning this to you to look into some more
