### ISSUE TITLE
Membership operations on `node.config` object fail

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt#3573]
### Describe the bug
When using membership operators (e.g. `"key" in node.config`) in `0.20.0`, you get an error "hasattr(): attribute name must be string". That is because this uses the `__iter__` method under the hood, which has been removed in https://github.com/dbt-labs/dbt/pull/3364/files#diff-007a86f768b23e1516e6d253d71656b96d46672fc7432dbc81d1d9445c98ca05L204-L231.

### Steps To Reproduce
I created a reproduction case in the testing suite here -> https://github.com/dbt-labs/dbt/compare/dbt-labs:f460d27...dbt-labs:8612ce4. 

### Expected behavior
This is a breaking change for folks who are doing these types of operations in their projects, I think it is worth maintaining consistency (https://getdbt.slack.com/archives/CBSQTAPLG/p1626195482486800)

**Comment by jtcohen6** [comment]
Python, what a magical thing...

Thanks for finding & filing @kwigley! Feels like a super quick fix, and definitely worth doing.

**Comment by leahwicz** [comment]
@gshank this might be a partial parsing bug. Could you please take a look?

**Comment by gshank** [comment]
This isn't a partial parsing bug per se. It's because I removed the MutableMapping superclass from the config class because of buggy behavior when serializing. I believe that all we have to do is add back the __iter__ method into the BaseConfig class.
