### ISSUE TITLE
python library dependency conflict

### ISSUE THREAD

**Issue by konkodi210** [dbt-labs/dbt#3574]
## steps to reproduce:
1. run pip install on attached [requirements.txt](https://github.com/dbt-labs/dbt/files/6818919/requirements.txt)
 ```shell
   pip install -r requirements.txt
```
2. System going to throw an error saying "request" having dependency conflict. 

## Observation
I looked the code, I see dependency on request was basically added for "snowflake". Hence  do we really need this dependency added for big query?
[requirements.txt](https://github.com/dbt-labs/dbt/files/6818919/requirements.txt)

**Comment by jtcohen6** [comment]
@konkodi210 It looks like your `requirements.txt` file includes `dbt-biguery==0.19.1` and [`apache-beam==2.30.0`](https://github.com/apache/beam/blob/c026c9fa00239a6f3650a6fa69f3aa864f692afe/sdks/python/setup.py#L157), which requires `'requests>=2.24.0,<3.0.0'`.

You're right that dbt v0.19 requires `requests<2.24.0`, to match the requirements in the pinned version of `snowflake-connector-python`:
https://github.com/dbt-labs/dbt/blob/745ae3e64ac03fedb19228b31252fea05eb0ed37/core/setup.py#L77-L78

Why coordinate these dependencies? We want to ensure that `pip install dbt`, which includes both `dbt-bigquery` and `dbt-snowflake`, will be able to succeed. However, we're thinking of formally separating their distribution.

In any case, I have good news. The latest version of dbt requires a newer version of `snowflake-connector-python`, one that has enabled us to significantly loosen the `requests` requirement:
https://github.com/dbt-labs/dbt/blob/a2caceb3255d86a7a3db4755e9f0fb347efcb712/core/setup.py#L79-L80

Try updating `requirements.txt` to:
```
dbt-bigquery==0.20.0
apache-beam[gcp]==2.30.0
```

**Comment by konkodi210** [comment]
Yes I did and it working.. Thanks for quick response
