### ISSUE TITLE
Package resolution is inconsistent for prerelease versions

### ISSUE THREAD

**Issue by lbk-fishtown** [dbt-labs/dbt#3578]
### Describe the bug
The incorrect package is installed using package/version syntax, but the correct package is installed using git/revision syntax.

### Steps To Reproduce

Set packages.yml to install 0.7.6 version of dbtvault.
Run dbt deps.

The wrong version of dbtvault is installed. Below packages.yml is set to 0.7.6 but b1 variation is installed.

Same behaviour on 0.19.1 and 0.20.0

### Expected behavior
Expected that the package version listed is the one installed.

### Screenshots and log output
```
❯ cat packages.yml
packages:
  - package: Datavault-UK/dbtvault
    version: 0.7.6
❯ dbt deps
Running with dbt=0.19.1
No profile "default" found, continuing with no target
Installing Datavault-UK/dbtvault@0.7.6-b1
  Installed from version 0.7.6-b1

Installing fishtown-analytics/dbt_utils@0.6.4
  Installed from version 0.6.4
```
### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: Not applicable.)

**The output of `dbt --version`:**
```
❯ dbt --version
installed version: 0.20.0
   latest version: 0.20.0

Up to date!
```

**The operating system you're using:**
OSX, but also occurs in dbt Cloud.

**The output of `python --version`:**
```
❯ python --version
Python 2.7.16
```

**Comment by jtcohen6** [comment]
Thanks for the report @lbk-fishtown. You're totally right, `dbt deps` with the package registry does not appropriately handle semantic versions with prerelease suffixes. As we continue to add packages to the Hub site, and support extended prerelease testing cycles, I think it's important for us to support this.

I managed to narrow down the issue, landing on the `compare` method in our semver logic:

https://github.com/dbt-labs/dbt/blob/f460d275baa4df8cf8713f27e198a3577d6ea71c/core/dbt/semver.py#L124-L159

This is not quite right—we need to make sure the final version supports range logic—but I can add a conditional like:
```python
        if not (
            self.prerelease == other.prerelease or
            (self.prerelease is None and other.prerelease is None)
        ):
            return 1
```
Then I can manage:
```yml
packages:
  - package: Datavault-UK/dbtvault
    version: 0.7.6
```
```
$ dbt deps
Running with dbt=0.20.0
Installing Datavault-UK/dbtvault@0.7.6
  Installed from version 0.7.6
Installing dbt-labs/dbt_utils@0.7.0
  Installed from version 0.7.0
```
While still supporting:
```yml
packages:
  - package: Datavault-UK/dbtvault
    version: 0.7.6-b1
```
```
$ dbt deps
Running with dbt=0.20.0-rc1
Installing Datavault-UK/dbtvault@0.7.6-b1
  Installed from version 0.7.6-b1
Installing fishtown-analytics/dbt_utils@0.6.4
  Installed from version 0.6.4
```
