### ISSUE TITLE
Make connect_timeout for Postgres/Redshift Adapters Configurable

### ISSUE THREAD

**Issue by JasonGluck** [dbt-labs/dbt#3581]
### Describe the feature
Make the connect_timeout for Postgres/Redshift Adapters configurable.

### Additional context
Affects both Redshift and Postgres adapters.

### Who will this benefit?
People who may be experience connection timeouts.

### Are you interested in contributing this feature?
Yes, will give it a try.

**Comment by jtcohen6** [comment]
Thanks for opening @JasonGluck! Let me know if you have questions as you get going :)
