### ISSUE TITLE
dbt build: Parity for flags

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt#3596]
Allow any flags set to be passed in to any of the tasks run in an invocation of `dbt build`.  In the case that a flag might apply to multiple types of tasks it applies to all tasks (it is an opinionated build command, after all)

**Comment by jtcohen6** [comment]
- Any flag that is supported by `run`, `test`, `seed`, `snapshot`
- `--resource-type` (like `list`)
- Ensure that the RPC method has parameters to support those flags as well
