### ISSUE TITLE
Incorrect package version being installed

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt#3609]
### Describe the bug
Despite having
```
  - package: tailsdotcom/dbt_artifacts
    version: 0.4.5a2
```

 set in packages.yml, running `dbt deps` results in 

```
Installing tailsdotcom/dbt_artifacts@0.4.5a1
  Installed from version 0.4.5a1
```

Sometimes this installs `0.4.5a2`, sometimes it doesn't. The same behaviour is also being seen in dbt cloud, and is causing frequent run failures. 0.4.5a2 is registered in dbt hub: https://hub.getdbt.com/tailsdotcom/dbt_artifacts/0.4.5a2/

### Steps To Reproduce
```
➜  git:(staging) dbt deps
dbtenv info:  Using dbt 0.19.1 (set by dbt_project.yml, dbt_modules/dbt_utils/dbt_project.yml, dbt_modules/codegen/dbt_project.yml, dbt_modules/dbt_artifacts/dbt_project.yml).
Running with dbt=0.19.1
Installing fishtown-analytics/codegen@0.3.1
  Installed from version 0.3.1

Installing tailsdotcom/dbt_artifacts@0.4.5a1
  Installed from version 0.4.5a1

Installing fishtown-analytics/dbt_utils@0.6.6
  Installed from version 0.6.6

➜  git:(staging) cat packages.yml
# Packages can be found on https://hub.getdbt.com/.
packages:
  - package: fishtown-analytics/dbt_utils
    version: [">=0.6.5", "<0.7.0"]
  - package: fishtown-analytics/codegen
    version: 0.3.1
  - package: tailsdotcom/dbt_artifacts
    version: 0.4.5a2
```

### Expected behavior
0.4.5a2 to be installed consistently

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.19.1
```

**The operating system you're using:**
Mac
**The output of `python --version`:**
3.8.9

**Comment by jtcohen6** [comment]
@NiallRees You're totally right, this is a bug in dbt's registry-based `deps` today: it doesn't treat prerelease versions properly. We just opened https://github.com/dbt-labs/dbt/issues/3578 for this last week, where I included a few links to the codepaths involved, so I'm going to close this issue as a dupe.

If you have the chance to check that out, and think it might be a feasible contribution, I'd very much welcome a PR for it. The code change may be tricky but should be fairly well self-contained.

**Comment by NiallRees** [comment]
> @NiallRees You're totally right, this is a bug in dbt's registry-based `deps` today: it doesn't treat prerelease versions properly. We just opened #3578 for this last week, where I included a few links to the codepaths involved, so I'm going to close this issue as a dupe.
> 
> If you have the chance to check that out, and think it might be a feasible contribution, I'd very much welcome a PR for it. The code change may be tricky but should be fairly well self-contained.

Thanks Jeremy I'll take a look
