### ISSUE TITLE
Allow custom adapters to replace default param marker in seed's basic_load_csv_rows

### ISSUE THREAD

**Issue by swanderz** [dbt-labs/dbt#3622]
### Describe the feature
Rather than overriding the entire `basic_load_csv_rows macro`, allow dbt adapters to override just the SQL parameter marker.

- `:p` (see [dbt-oracle's `seed.sql`](https://github.com/techindicium/dbt-oracle/blob/fa9718809840ee73e6072f483233f5150cc9986c/dbt/include/oracle/macros/materializations/seed/seed.sql#L20-22))
- `?` (see [dbt-sqlserver's `seed.sql`](https://github.com/dbt-msft/dbt-sqlserver/blob/75ff846ae0fbb93c41e7f93c087a24a1e19bb7e0/dbt/include/sqlserver/macros/materializations/seed/seed.sql#L34), [dbt-ibmdb2's `seed.sql`](https://github.com/kaysef/dbt-ibm-db2/blob/b01548c2057d6df76cb285d0f4168a6c8fdef064/dbt/include/ibm_dbt/macros/materializations/seed/seed.sql#L18) and other as of yet unreleased database adapters...)

### Describe alternatives you've considered

overriding the whole macro is what's currently done

### Additional context

relevant for the [pyodbc](https://github.com/mkleehammer/pyodbc), [cx_Oracle](https://oracle.github.io/python-cx_Oracle/),  and [JayDeBeApi](https://github.com/baztian/jaydebeapi) drivers 

### Who will this benefit?

This benefits adapter maintainers not having to keep the `basic_load_csv_rows` macro up to date and keep their respective adapter repo code footprint smaller, thus more easily maintained and compatible with future changes

### Are you interested in contributing this feature?
PR coming right up!

**Comment by jtcohen6** [comment]
Thanks @swanderz, this makes sense to me! I'll take a look at the PR and leave comments.
