### ISSUE TITLE
Fix Experimental Parser So Tests Pass

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt#3640]
### Describe the bug
Running the postgres integration suite with the experimental parser always on results in a failure. 

### Steps To Reproduce
Run the following with the line `flags.USE_EXPERIMENTAL_PARSER = True` in `models.py::render_update`:
```
python3 -m pytest test/integration/039_config_test/test_configs.py::TestConfigs::test_postgres_config_layering
```

You get the following failure:
```
dbt.exceptions.CompilationException: Compilation Error
E         The selection criterion 'tag:tag_two' does not match any nodes
```

### Expected behavior
This test seems to be reasonable so we expect it to pass.

### Additional context
If a release goes out with this problem it will cause the tracking to have an outsized proportion of mismatches rendering the tracking for that version fairly useless.

**Comment by gshank** [comment]
There are config settings besides 'tags' which have MergeBehavior. 'post-hook' and 'pre-hook' also work like tags, and the dictionary configs are generally 'Update' (merging the dictionaries), which is true of 'quoting'. And in my configs-in-schema-file ticket I add a 'meta' config which is also Update. Would it be simpler to provide separate config dictionaries for each call?
