### ISSUE TITLE
Issue with snapshot using delta on spark-dbt

### ISSUE THREAD

**Issue by ashishmgofficial** [dbt-labs/dbt#3655]
### Describe the bug
Hi All,
Im creating snapshot using Delta using local spark. But after the Initial snapshot, from the second dbt snapshot command, im getting the error snapshot `target is not a snapshot table (missing "dbt_scd_id", "dbt_valid_from", "dbt_valid_to")`.
Im guessing this is because the select statement doesnt contain these fields as these are generated by dbt. But is there something Im missing or do we need to add these to select statement manually  from second run ? Any help would be great !

### Steps To Reproduce
1) Connect dbt to Spark Thrift server
2) create a snapshot query using delta with followiing configs :
     file_format=delta
     unique_key= your unique key
     strategy= timestamp
     updated_at = your timestamp column

    

### Expected behavior
scd2 operation on all `dbt snapshot`  queries

### Screenshots and log output
 `target is not a snapshot table (missing "dbt_scd_id", "dbt_valid_from", "dbt_valid_to")` from second `dbt snapshot` command

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify:  spark ( local ))

**The output of `dbt --version`:**
```
0.20.0
```

**The operating system you're using:**
RHEL 7 , Ubuntu etc
**The output of `python --version`:**
python3.9.6, python3.8

**Comment by jtcohen6** [comment]
Thanks for opening @ashishmgofficial, and apologies for the delay following up.

I see you've opened https://github.com/dbt-labs/dbt-spark/issues/199 and a [stackoverflow thread](https://stackoverflow.com/questions/68626732/issue-with-snapshot-using-delta-on-spark-dbt) as well. I think the `dbt-spark` issue is going to be the best place for this discussion.

It's worth noting that the specific validation error you're seeing is defined in this repo, in the base adapter:
https://github.com/dbt-labs/dbt/blob/159e79ee6ba86c852f4bf067dd0f1b6356135383/core/dbt/adapters/base/impl.py#L636-L648

Given that this isn't an error we're seeing on other adapters, that snapshots are especially vulnerable to the specific implementation details of their adapter/storage context, and the fact that `dbt-spark` reimplements its own `snapshot` materialization, I think the Spark context here is going to be quite important.

Let's continue debugging over in https://github.com/dbt-labs/dbt-spark/issues/199!
