### ISSUE TITLE
Publishing Docker images to Amazon ECR Public registry

### ISSUE THREAD

**Issue by moltar** [dbt-labs/dbt#3681]
#### Problem

Using Docker Hub public registry can be problematic, as there are now [rate limits](https://www.docker.com/increase-rate-limits) for the free plan. The fee isn't an issue in itself, and IMO is fine. It's just when using the image inside CI/CD pipeline can cause issues, as the registry needs to be authenticated, which means storing secrets.

This is especially problematic when using AWS CodePipeline as it shares build servers and/or IPs, and often builds fail due to rate limiting.

#### Solution

Publish Docker images to Amazon ECR Public registry.

### Describe alternatives you've considered

N/A

### Additional context

 - [Quick start: Publishing to Amazon ECR Public using the AWS CLI ](https://docs.aws.amazon.com/AmazonECR/latest/public/getting-started-cli.html)
 - [Getting Verified account badge](https://docs.aws.amazon.com/AmazonECR/latest/public/public-gallery.html)
 - [Amazon ECR Public registry](https://gallery.ecr.aws/)
 - [ECR](https://aws.amazon.com/ecr/)

### Who will this benefit?

Users of AWS who wish to use Docker images for dbt.

### Are you interested in contributing this feature?

Maybe.

**Comment by jtcohen6** [comment]
@moltar Thanks for opening, and for providing that context about the less-than-ideal interaction between DockerHub rate limiting and AWS CodePipeline.

In a couple of weeks, as part of the lead-up to v1.0, we're going to take another look at our overall distribution strategy (https://github.com/dbt-labs/dbt/issues/3361). In all likelihood, we'll start pushing a separate Docker image for each warehouse adapter that we maintain.

@kwigley and I (among other folks) are going to spend some time thinking about which image registry (or registries) makes the most sense. I don't _think_ we're going to opt for any cloud-specific registries (Amazon ECR, GCP Container Registry, Azure Container Registry), but I can't say that for sure until we've had a chance to discuss in more detail. At the very minimum, we'd be creating a new DockerHub org named `dbt-labs`, and we'd stop pushing to the one named `fishtownanalytics` :)

I'm going to close this issue for the time being, not to say that it's a definite no, but just to say that we'll be revisiting this in a handful of weeks, and we'll be considering DockerHub's rate limiting as one consideration among many.

**Comment by moltar** [comment]
@jtcohen6 Thank you for your reply. Understood.

I believe it's essential to have official images at all major registries due to security concerns.

If you don't publish your own image, someone else will and that image will gain traction. It may have bugs from the image author or eventually be compromised in some way.

I understand it can be tedious to maintain support for multiple registries, but I'm sure dbt community would help.

I can certainly help with ECR.

**Comment by jtcohen6** [comment]
@moltar Good points all around. Thanks again for opening, and for starting the conversation. All the more reason for us to develop a more comprehensive plan around image registries.

**Comment by moltar** [comment]
Might be helpful: https://github.com/xelalexv/dregsy
