### ISSUE TITLE
compiled sql is over-riding the model in DBT

### ISSUE THREAD

**Issue by arpitajaiswal311** [dbt-labs/dbt#3683]
**Describe the bug**
I have my dbt_project.yml and profiles.yml files in a custom path i.e. outside my project folder. I have also mentioned the "models" and "macros" paths in dbt_projects.yml, so that it is referring to the respective directories. After executing "dbt run --profile-dir path_to_profiles.yml --project-dir path_to_dbt_project.yml", my models are over-written by the compiled sql. Ideally the compiled sql should be stored under "target/compiled/project_name/models/" folder.

Note: I am using dbt-spark.

Below is the dbt_project.yml file:
name: '<project_name>'
version: '1.0.0'
config-version: 2

profile: demo_dbt

source-paths: ["home_directory/project_name/models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["home_directory/project_name/macros"]
snapshot-paths: ["snapshots"]
log-path: "logs"
target-path: "target"  
clean-targets:         
     - "target"
     - "dbt_modules"

models: 
                 
vars:
	db_name: demo_db
	table_name: demo_table
	

Any help would be appreciated.
Thanks in advance.

**Comment by jtcohen6** [comment]
Thanks for the report @arpitajaiswal311. This is a known issue (https://github.com/dbt-labs/dbt/issues/2669), and a pretty ugly one. I'd definitely welcome a contribution to fix this, if you'd be interested in diving into the details over there.

In the meantime, would you be up to add a note to [the `source-paths` docs](https://docs.getdbt.com/reference/project-configs/source-paths) ([edit here](https://github.com/dbt-labs/docs.getdbt.com/edit/current/website/docs/reference/project-configs/source-paths.md))? The problem arises whenever `source-paths` is set to an absolute path.
