### ISSUE TITLE
Add sort to snapshot configurations

### ISSUE THREAD

**Issue by BrieucVanThienen** [dbt-labs/dbt#3692]
**Describe the feature**

It appears that setting sort keys for snapshots in the snapshots config, just like it is usually done for models, is currently not supported. The feature would hence consist in adding `sort` to the snapshot configurations.

**Describe alternatives you've considered**

Envisaged to set the sort keys through post-hooks. It appeared that it would work on the first run, but not on the subsequent runs. The following error was returned when testing: `ALTER TABLE ALTER SORTKEY cannot alter to the same sort keys`. 

We envisaged to run the command only once manually, but it would only be temporary until the schema of the snapshot changes (when adding or removing columns), and the snapshot needs to be re-built.

**Who will this benefit?**

Advanced users of snapshots.

**Are you interested in contributing this feature?**

This is my first issue so would need to be guided through the steps. But nothing against it.

**Comment by jtcohen6** [comment]
Hey @BrieucVanThienen, I think this should work!

Adapter-specific configs, such as `sort` and `dist` on Redshift, are supported for snapshots just as they are for models. Given the nature of those configs, which are [templated into the `create table` statement](https://github.com/dbt-labs/dbt/blob/0efaaf7dafccb3329ade084a14218e73e8e83b08/plugins/redshift/dbt/include/redshift/macros/adapters.sql#L32-L52), they will only take effect on the initial `dbt snapshot`. If you want to add a sort key to an existing snapshot, manually running `alter table alter sortkey` is probably the way to go.

```sql
{% snapshot my_snap %}

{{
    config(
      target_schema='snapshots',
      unique_key='id',
      sort='int_col',
      strategy='timestamp',
      updated_at='updated_at',
    )
}}

select 1 as id, 100 as int_col, current_timestamp as updated_at
union all
select 1 as id, 100 as int_col, current_timestamp as updated_at

{% endsnapshot %}
```
From `logs/dbt.log`:
```
 create  table
    "analytics"."snapshots"."my_snap"
    
    
      compound sortkey(int_col)
  as (
    

    select *,
        md5(coalesce(cast(id as varchar ), '')
         || '|' || coalesce(cast(updated_at as varchar ), '')
        ) as dbt_scd_id,
        updated_at as dbt_updated_at,
        updated_at as dbt_valid_from,
        nullif(updated_at, updated_at) as dbt_valid_to
    from (
        



select 1 as id, 100 as int_col, current_timestamp as updated_at
union all
select 1 as id, 100 as int_col, current_timestamp as updated_at

    ) sbq


  );
```
