### ISSUE TITLE
DBT RPC server can't access Snowflake after dbt upgraded from 0.19 to 0.20 and 0.21 beta

### ISSUE THREAD

**Issue by eugene-nikolaev** [dbt-labs/dbt#3695]
### Describe the bug
Hello!
Our setup, involving dbt as an rpc server, worked well on dbt 0.19.1.
After upgrade to 0.20 everything works locally but rpc server doesn't, it fails with an error (below)

### Steps To Reproduce
- install dbt 0.20
- run as an rpc server
- try to run any command on rpc server

### Expected behavior
dbt transformations are being performed

### Screenshots and log output
```
FailedToConnectException: Database Error\n  250003: Failed to get the response. Hanging? method: post, url: https://<...>.eu-central-1.snowflakecomputing.com:443/session/v1/login-request?request_id=9bec6327-45ec-4d9c-968b-cfa2cbd0036c&databaseName=dev_data_mart&schemaName=dbt_evgeniin&warehouse=compute_wh&roleName=dbt_dev&request_guid=7986c1d3-ed82-45ad-92b0-4215c204ca0b"}]}}, "id": "fcb1b726-f5e5-11eb-bf1d-06edb87e16c9", "jsonrpc": "2.0"}
```
Note that Snowflake account is wiped out from this log.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - bigquery: 0.20.0
  - snowflake: 0.20.0
  - redshift: 0.20.0
  - postgres: 0.20.0
```

With 0.21 beta as well (wanted to try if that was fixed)

**The operating system you're using:**
MacOS

**The output of `python --version`:**
```
Python 3.7.7
```

**Comment by jtcohen6** [comment]
@eugene-nikolaev Thanks for the report. We've been able to successfully use `dbt rpc` + Snowflake in v0.20.0, so there must be something else going on.

The error you're seeing comes from `snowflake-connector-python`'s [`snowflake.connector.network._handle_unknown_error`](https://github.com/snowflakedb/snowflake-connector-python/blob/77725c8e30e4c7fa24d5a37d41bffc3192a53449/src/snowflake/connector/network.py#L857-L890) method. That's not much help in determining what's going on here, but I do think it indicates that the bug isn't with `dbt rpc`.

Have you been able to use other dbt CLI commands, such as `dbt debug`?

**Comment by eugene-nikolaev** [comment]
Hi @jtcohen6!
Thanks for reply and sorry, I didn't check one possible cause.
This was because of proxy.
I still don't know why 0.19 works but 0.20 doesn't - that might be some difference in `snowflake-connector-python` as well, but without proxy it works well.
