### ISSUE TITLE
Cannot process CSV fields longer than maximum length

### ISSUE THREAD

**Issue by gsc** [dbt-labs/dbt#3704]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

Tried loading a CSV seed file into a postgres database, with a field larger than the default field_size_limit. 
This failed returning the following error message:

```
Completed with 1 error and 0 warnings:

CSV contains fields longer than maximum length of 131072 characters. Try raising the maximum with the field_size_limit parameter, or try setting quoting=csv.QUOTE_NONE.
``` 
This seems to be bubbled up from the csv standard library from python, which produces this error when reading csv fields that are longer than the default max length value.  When using the CSV libary, this seems to be solved by setting up a higher field_size_limit (see [SO link](https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072) for examples on how this is solved), but when using dbt,  we don't have a way to set that parameter. 

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Run a dbt seed with a CSV file that has one column over 131072 chars. 

### Expected behavior

Be able to setup a different limit on the CSV field size (using some configuration setting in the dbt project?). 

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

```
Found 4 models, 4 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 2 seed files, 0 sources

18:31:57 | Concurrency: 1 threads (target='dev')
18:31:57 | 
18:31:57 | 1 of 2 START seed file public.italy_raw_geofences.................... [RUN]
18:31:57 | 1 of 2 OK loaded seed file public.italy_raw_geofences................ [INSERT 43 in 0.11s]
18:31:57 | 2 of 2 START seed file public.poa_2016............................... [RUN]
Unhandled error while executing seed.clinigen.poa_2016
CSV contains fields longer than maximum length of 131072 characters. Try raising the maximum with the field_size_limit parameter, or try setting quoting=csv.QUOTE_NONE.
18:31:57 | 2 of 2 ERROR loading seed file public.poa_2016....................... [ERROR in 0.34s]
18:31:57 | 
18:31:57 | Finished running 2 seeds in 0.65s.

Completed with 1 error and 0 warnings:

CSV contains fields longer than maximum length of 131072 characters. Try raising the maximum with the field_size_limit parameter, or try setting quoting=csv.QUOTE_NONE.

Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

### System information
**Which database are you using dbt with?**
- [ x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.2
   latest version: 0.20.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.18.2
  - redshift: 0.18.2
  - snowflake: 0.18.2
  - bigquery: 0.18.2
```

**The operating system you're using:**

```
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 33 (Thirty Three)
Release:	33
Codename:	ThirtyThree
```

**The output of `python --version`:**

``` 
Python 3.8.11
```

**Comment by jtcohen6** [comment]
@gsc Thanks for opening! I'm not rejecting this proposal out of hand, but I am inclined to think that it goes beyond the recommended and supported use case for `dbt seed`.

Seeds are designed for small, human-readable datasets that are checked into version control. When the data in a seed does change (infrequently), those changes occur via manual edits, proposed and reviewed as a pull request.

Seeds are not designed for loading actual source data, or for handling datasets of any substantial size. We generally set that bar at 1 MB. Reasons why:
- `dbt seed` loads data into memory, and then into the database in 10k row batches. This is quite memory- and time-intensive for large datasets!
- dbt stores a checksum of seed contents to power [state comparison](https://docs.getdbt.com/docs/guides/understanding-state), but it will not store a checksum of any seed that is >1 MB in size

If you have a seed with a field that's 131072 characters, 10 rows of that seed will add up to >1 MB of data (right?). I also have a hard time imagining a human being editing/reviewing changes to that field!

So: What type of data are you attempting to seed? Is it geospatial/image data? Could you stage it and load/query it from somewhere else, such as external storage (S3 / GCS / Azure blob / etc)?

**Comment by gsc** [comment]
Yes, in my particular case it is geospatial data (it's not very frequent, but Multipolygons of certain complexity may grow large pretty fast). I have indeed managed to load by using external storage S3 as a workaround, while waiting for this to be "solved", but your description of the intended usage for seeds seems pretty reasonable, so probably there's nothing to be fixed here. Many thanks for the detailed explanation.

**Comment by RobMcZag** [comment]
Hi, I would like to reopen it, asking dbt to provide some way to enter a config to override that reasonable maximum.

In my case I have a CSV with 4 rows delimiting the 4 test area of interest for a project.
I need to load that "quickly" to provide data filtered by such 4 bounding multi-polygons and I do not have easy / quick access to place the CSV in some storage to read it with a copy into.

I think that this is exactly one of the good use cases for SEEDs: loading a human maintained CSV with the (machine generated) shape of test areas.

**Comment by alecburnett** [comment]
I agree with @RobMcZag - think this needs to be looked into.

I also have uses cases where the bulk of the fields are manually editable - but has a geometry field as the last field. Of course no one will edit this. But the other attributes aboslutely yes.

Any geometry that isn't a point will run into this field limit issue.

Additionally - more teams are starting to incorporate spatial operations in DBT modelling - so think you'll start getting these complaints more frequently over time.

**Comment by HonorableVC** [comment]
For those looking for a quick fix. 
In the follow: `[ Path to Python Virtual Environment ]/lib/python[ Python Version ]/site-packages/dbt/__init__.py`

add the following 2 lines

```python
import csv
csv.field_size_limit([ Desired Size ])
```
