### ISSUE TITLE
Add support for BigQuery execution project in BigQuery adapter

### ISSUE THREAD

**Issue by Kayrnt** [dbt-labs/dbt#3708]
### Describe the feature
This feature adds support for BigQuery execution project in BigQuery adapter through the adapter profile configuration so that the database client uses slots from the reservation assigned to that project as explained in [BigQuery documentation](https://cloud.google.com/bigquery/docs/reservations-intro).

My current workaround is to use the project I want to use the reservation on through the adapter profile configuration and specify the project in the `dbt_project.iml` for models to ensure the outputs are in the appropriate project.

### Describe alternatives you've considered
Another approach would be to use the `project` for the database client and to provide a `database_project` to use it as the default project for storing the outputs (opposed to the `project` that would be used for execution).

### Additional context
This feature is only relevant to BigQuery as far as I know.

### Who will this benefit?
It will be useful for any company using multiple BigQuery reservations/projects (such as the one at work at).
Regarding current workaround I use, it's clearly inconvenient as we remove the database override when we're working with a development environment and we have to remember not to commit it as we're versioning our `dbt_project.iml`.

### Are you interested in contributing this feature?
Yes, I'm just not sure it's really testable beside checking it's properly reading the appropriate field in the configuration.

**Comment by jtcohen6** [comment]
Thanks for opening @Kayrnt! This was originally open in #2918. At the time I had reservations about its necessity, given the possibility of the alternative you described; since then I've come around to it.

I'll take a look over in #3707!

**Comment by Kayrnt** [comment]
Hello @jtcohen6, glad to hear that it's a feature you considered.
Thanks for reviewing! I looked for similar issues but didn't check for closed issues!

The workaround I described is the single option I found to work with our setup and since it's not intuitive I've documented it in our own DBT project. At my current company, we have a similar internal tool to DBT and there are 3 features that DBT misses to catch up in my point of view:
- BigQuery execution project usage (This issue)
- Support for creating BQ tables using partitioning & clustering configuration (I think there is already an issue for that)
- Support for adding/deleting columns to an existing BQ table (I think it's coming in 0.21 with https://github.com/dbt-labs/dbt/issues/1132 but I use `materialized='table'` so I'm not sure it would work).

I hope I'll be able to contribute to enhance DBT!

**Comment by jtcohen6** [comment]
@Kayrnt Ah very cool! The second and third features you mention are things that dbt already supports:
- via `partition_by` + `cluster_by` configs ([docs](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#using-table-partitioning-and-clustering))
- Every time you run a `table`-materialized model, dbt runs a full `create or replace`, so any column additions/deletions there are handled automatically. It's only when you're using `materialized: incremental` that this gets trickier, which is what the `on_schema_change` config in v0.21 is going to help address ([prerelease docs for that](https://next.docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#what-if-the-columns-of-my-incremental-model-change))

**Comment by Kayrnt** [comment]
Thanks for the information!

For clustering & partitioning, last time I have tested (probably a 0.18.x), it didn't work with my configuration, I'll double check as I recently bumped to 0.20.0.
I think it might be because I use "partition" option to create daily tables that it doesn't create with proper keys and I might move to incremental. I recall not using incremental because there used to be a bug with UDFs and I ran into issues for running partitions with incremental back in 0.18.x.
I'll double check with the latest version and create appropriate issues if I can reproduce (or look for existing ones).

**Comment by Kayrnt** [comment]
@jtcohen6 I think I found out what's the issue for remark on `Support for creating BQ tables using partitioning & clustering configuration`:
Let's take a simple query such as 
```
{{
    config(
        materialized='table',
        partitions=dbt.partition_range(var('dates', default=yesterday_table_format())),
        partition_by={
          "field": "date",
          "data_type": "date"
        },
        cluster_by = ["field1", "field2"],
    )
}}
SELECT
 DATE("2021-08-15") AS date,
 1 AS field1,
 2 AS field2,
 3 AS field3
```

Produce appropriate table through
```
  create or replace table `gcp_project`.`dbt_kayrnt`.`test_query`
  partition by date
  cluster by field1, field2
  OPTIONS()
  as (

SELECT
 DATE("2021-08-15") AS date,
 1 AS field1,
 2 AS field2,
 3 AS field3
  );
```

But if I add `partitions=dbt.partition_range(var('dates', default=yesterday_table_format())),` then it will fallback to the default partitioning (_PARTITIONTIME field) and not use the partition_by definition nor the clustering one.

I guess there are multiple ways to "fix" that:
- Make explicit that `partitions` is not compatible in https://docs.getdbt.com/docs/guides/database-specific-guides/creating-date-partitioned-tables and maybe through a warning at queries compile time
- Change priority so that partition_by takes over partitions and use that field if the field is a date. It would then be interesting to extend it to support integer ranges and hour ranges too.

Anyway I didn't look so far how the table created when using `partitions` 
but I think it could be moved to the 
```
 create or replace table `gcp_project`.`dbt_kayrnt`.`test_query`
  partition by _PARTITIONDATE
```

as described in https://cloud.google.com/bigquery/docs/creating-partitioned-tables#create_an_ingestion-time_partitioned_table.

Does it make sense? Should I create an issue?

Also I think there is a bug on that `partitions` feature: if you use `dbt run --models partitioned_yesterday --vars 'dates: "20180101, 20180103"'` example to backfill a range. It will use 'generate' the query once and something like 
```
{%- if "20180102" <= "[DBT__PARTITION_DATE]" %}
my_field,
{%- else %}
null as my_field,
{%- endif %}
```
would be mean that if your range start start before or at `20180102` it will use `null as my_field,` even if it evaluates for after `20180102` (ie `20180103`).

I personally like that feature as opposed to `incremental` approach, it lets me process one day per actual query which fits very well our use case at my current job (known as `jobHistory` in [the last part of one of our tech articles](https://medium.com/teads-engineering/give-meaning-to-100-billion-events-a-day-part-ii-how-we-use-and-abuse-redshift-to-serve-our-data-bc23d2ed3e07)) and that's why I would love to see `on_schema_change` for table as well though I didn't try the combination of both `materialized: incremental` with `partitions` and reading [documentation about it](https://next.docs.getdbt.com/reference/resource-configs/bigquery-configs#static-partitions), it might work as I expected it to through my current usage of `materialized: table` with `partitions`.
