### ISSUE TITLE
`test_type:` method uses old test types

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt#3719]
### Describe the bug
As [documented here](https://docs.getdbt.com/reference/node-selection/methods#the-test_type-method) `test_type:` accepts `data` and `schema` instead of `bespoke` and `generic`.

### Steps To Reproduce

```
dbt test -m test_type:bespoke
dbt test -m test_type:generic
```

### Expected behavior
The selectors to work ;)

```
$ dbt test --m test_type:generic
Running with dbt=0.20.1-rc1
Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
Partial parsing enabled, no changes found, skipping parsing
Found 145 models, 749 tests, 0 snapshots, 0 analyses, 341 macros, 0 operations, 4 seed files, 67 sources, 0 exposures
Encountered an error:
Runtime Error
  Invalid test type selector generic: expected "data" or "schema"
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```
installed version: 0.20.1-rc1
   latest version: 0.20.0

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.20.1rc1
  - snowflake: 0.20.1rc1
  - redshift: 0.20.1rc1
  - postgres: 0.20.1rc1
```

**The operating system you're using:** Mac

**The output of `python --version`:** 3.8.10

### Additional context
While I'm running the 0.20.1rc, I don't believe this to be an issue specific to the RC

**Comment by jtcohen6** [comment]
@jaypeedevlin You're 100% right! Thanks for opening the issue, it's one of a few things that prompted me to rekindle the conversation over in https://github.com/dbt-labs/dbt/issues/3234. I'd love to get your thoughts there about where we're landing: definitely sticking with `generic`, but leaning `singular` over `bespoke`

I'm going to close this issue in favor of that one, to keep the conversation centralized there. Once we have a final verdict, it's time for find+replace in the codebase.
