### ISSUE TITLE
run_sql rpc method casts number-like strings to numbers

### ISSUE THREAD

**Issue by tom-james-watson** [dbt-labs/dbt#3756]
### Describe the bug

If you execute some sql via the `run_sql` rpc method that will return string values that look like numbers, the values are erroneously cast to numbers.

This seems to happen for anything that looks like a number, e.g.:

* `'0.55'` -> `0.5`
* `'-10'` -> `-10`
* `'+12024561111'` -> `12024561111`
* `'0.000000000000000001'` -> `5e-18`

This *doesn't* happen when you actually run the model. The materialized view shows the string value as expected.

### Steps To Reproduce

Execute the following via the `run_sql` rpc method:

```
select '+1' as test
```

You will see the following in the response:

```
...
"table": {
  "column_names": [
    "test_value"
  ],
  "rows": [
    [
      1
    ]
  ]
}
...
```

### Expected behavior

```
...
"table": {
  "column_names": [
    "test_value"
  ],
  "rows": [
    [
      "+1"
    ]
  ]
}
...
```

### System information

**Which database are you using dbt with?**

- [x] postgres
- [x] redshift
- [x] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

Have confirmed on 0.15.0 through to 0.20.1.

**The operating system you're using:**

Linux and macOS.

**The output of `python --version`:**

3.6

**Comment by jtcohen6** [comment]
@tom-james-watson Thanks for the detailed report! We've recently resolved this (https://github.com/dbt-labs/dbt/pull/3499); that fix will be going out in the next minor version of dbt (v0.21.0).

You can try installing [v0.21.0b1](https://github.com/dbt-labs/dbt/releases/tag/v0.21.0b1) yourself to test:
```sql
select '+1' as test
```
```json
{
    "jsonrpc": "2.0",
    "method": "run_sql",
    "id": "2db9a2fe-9a39-41ef-828c-25e04dd6b07d",
    "params": {
        "timeout": 60,
        "sql": "c2VsZWN0ICcrMScgYXMgdGVzdA==",
        "name": "my_first_query"
    }
}
```
```json
...
"table": {
    "column_names": [
        "test"
    ],
    "rows": [
        [
            "+1"
        ]
    ]
},
...
```
