### ISSUE TITLE
Unexpected occurrences of partial parsing version mismatch

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt#3757]
From dbt community slack:

JC, I'm now using the 0.20.1 actual release and I'm still seeing occasions of Unable to do partial parsing because of a dbt version mismatch on runs.  It's not happening on every run, but it's definitely happening with regularity.
I'm having trouble generating a reproducible case (which is why I haven't opened an issue), but it's happening (with this project anyway) at least 1 in 3 runs.  I can't see anything that seems relevant in the logs, but I wanted to call it out in case (a) you hear of this elsewhere and (b) there's anything I can do to give you more context to understand why this might be happening.

Two consecutive commands were shared, both reporting the same version, with the second one claiming a version mismatch.

**Comment by gshank** [comment]
The version in the partial_parse.msgpack file ought to be set from the __version__ variable in core/dbt/version.py, and is compared against that variable when loaded. So this is pretty strange. I'm going to add information to the version mismatch log message containing the manifest.metadata.dbt_version string and the __version__string, and also verify that that the dbt_version is set correctly right before the manifest is saved. After that, the only thing I can think of is some weird serialization error, which has never happened for us.

**Comment by jaypeedevlin** [comment]
Hey folks, I haven't seen this one in a while but it's popped up in a project I'm working on today.  Per the screenshot below you can see the first partial parse worked fine, and then it started complaining about a mismatch again.

![image](https://user-images.githubusercontent.com/17235807/133849643-a810eec5-b195-4eca-a9b5-75800103d02c.png)

No major complaints on my end as this is a small project that passes fast without partial parsing, just sharing this in case it's useful!

**Comment by leahwicz** [comment]
@jtcohen6 @gshank the version mismatch error is back ☝️ but as least we don't fail anymore with it. Still something we should take a look as to why it's happening.

**Comment by jaypeedevlin** [comment]
@notAmine this is an expected error when you're upgrading between versions, but it should only occur once.

If it's not, the most likely culprit (in my experience) is something else compiling your project with a different version, eg dbt Power user vscode extension (reading the messages above I'm honestly not convinced this wasn't my issue originally and that this is a false positive, but couldn't be certain).
