### ISSUE TITLE
Add docker usage to documentation

### ISSUE THREAD

**Issue by telenieko** [dbt-labs/dbt#3768]
This is brought from #1944 ([@bcdady's comment](https://github.com/dbt-labs/dbt/issues/1944#issuecomment-899645849)), which is currently closed (it was about creating a Dockerfile, not documenting that).

The are now [official docker images ](https://hub.docker.com/u/fishtownanalytics) published for dbt, but it is mostly undocumented. Searching for dbt & docker will most likely get you to #1944 and unofficial images.

Maybe a note could be added to the bottom of <https://docs.getdbt.com/dbt-cli/installation> informing of those images existance?

**Comment by jtcohen6** [comment]
Thanks @telenieko! I completely agree, and I had (still have) an in-progress PR over in the docs.getdbt.com repo to do just this: https://github.com/dbt-labs/docs.getdbt.com/pull/638

As it happens, in a few weeks we'll be taking another pass at our distribution and release processes for dbt, including a split-up of adapter plugins (#3361) and revisiting our Docker image publication/registry strategy (see conversation in #3681)—both part of the lead-up to dbt v1.0 later this year. After we do that, I'm going to take another pass at the docs PR, and officially document our `dbt-<adapter>` docker images.

I'm going to close this issue in the meantime; it's on our near-term radar.

**Comment by leonard-mandtler** [comment]
Hi @jtcohen6,
As dbt v.1.0.0 is released now, I wonder, when the documentation on Docker will follow. I am just starting with dbt and it would be really helpful to have documentation available here: https://docs.getdbt.com/dbt-cli/install/docker
Thanks!
