### ISSUE TITLE
dbt-extractor license

### ISSUE THREAD

**Issue by lautis** [dbt-labs/dbt#3821]
Could you clarify dbt-extractor license situation? The package does not have any license attached to it. As there is no license, I'm not sure if I have the right to use dbt-extractor and by extension dbt.

The repository for dbt-extractor seems to be private, so I'm opening an issue here.

**Comment by jtcohen6** [comment]
The repo is now public with an Apache 2.0 license: https://github.com/dbt-labs/dbt-extractor

We've also updated the python package metadata, so future versions on PyPi should reflect the license and link back to the OSS repo.

**Comment by lautis** [comment]
Thank you for the swift resolution! 🙏
