### ISSUE TITLE
Show a pass/fail count for all steps tested during dbt debug, to avoid issues being pushed below the fold

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt#3831]
### Describe the feature
When running `dbt debug` in a short terminal window (e.g. in VS Code on a laptop), issues can be pushed out of the viewport. In this example, `dbt_project.yml` is missing:
![image](https://user-images.githubusercontent.com/7335046/131306922-ae25ad9a-f567-4c8d-9b58-159e9ba57ba5.png)

In fairness, there is an error message there but at a glance it just looks like the cwd prompt. The green `OK connection ok` message above absolutely smokes it in a competition for attention. 

```
$dbt debug
Running with dbt=0.21.0-b1
...
Using dbt_project.yml file at C:\WF\LP\data-insights\dbt-core\dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [ERROR not found]

Required dependencies:
 - git [OK found]

Connection:
...
  Connection test: OK connection ok

3/4 checks passed #in red 
Could not load dbt_project.yml
```

### Describe alternatives you've considered
Reading the error message that's already on screen. 

### Additional context
This bit me hard the first time I ran debug. It just caught me again but I was wiser this time. 

I'm not sure if it's 4 checks, or whether it's also checking things like Python version and path. Let me know if it's more complex than just the 4 that get an OK/ERROR outcome.

### Who will this benefit?
Most of all, new users on their first run through. 

### Are you interested in contributing this feature?
Yep! I've already had a look around the region and it looks pretty straightforward.

**Comment by jtcohen6** [comment]
@joellabes Thanks for opening, makes a lot of sense to me! I'll take a look at the companion PR.
