### ISSUE TITLE
0.20.1 tests `where` config does not support models with periods in the name

### ISSUE THREAD

**Issue by karklin** [dbt-labs/dbt#3857]
### Describe the bug

I'm trying to execute in BigQuery a `not_null` test on a model that includes a period in its name. Here is the relevant part of the `schema.yml`:
```
models:
  - name: staging.my_table_name
    columns:
      - name: reset_length
        tests:
          - not_null:
              where: "reset_unit != 'LIFETIME'"
```
The generated SQL for the test uses the model name as the alias, unquoted, which is not valid BigQuery SQL:
```
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
select *
from (select * from `project-name`.`dataset_name`.`staging__my_table_name` where reset_unit != 'LIFETIME') staging.my_table_name
where reset_length is null
    ) dbt_internal_test
```

### Steps To Reproduce
Create a model with a period in its name, for example `staging.my_table.sql` and include a `not_null` test with a `where` condition in the schema.

### Expected behavior
Expected behavior is valid SQL that test not-NULL values of columns under the given WHERE condition.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.1
   latest version: 0.20.1

Up to date!

Plugins:
  - bigquery: 0.20.1
  - snowflake: 0.20.1
  - redshift: 0.20.1
  - postgres: 0.20.1
```

**The operating system you're using:**
mac OS X 11.4 big sur

**The output of `python --version`:**
`Python 3.8.5`

**Comment by jtcohen6** [comment]
Thanks for opening the issue @karklin! I agree, the way we (I) implemented the `where` config for tests was a bit odd. In an attempt at complete backwards compatibility, I thought to alias any subquery with the model name... but it's not like generic test definitions could really count on a consistent model name, anyway.

So: I'd like to rework the way we template in the `where` config, with a couple of goals:
- resolve this issue
- make `test_metadata.model` in `manifest.json` more readable
- enable adapter plugins + users to reimplement the `where` subquery logic
