### ISSUE TITLE
Turn on partial parser by default

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt#3867]
Pre-req before turning on:
- [x] https://github.com/dbt-labs/dbt/issues/3810
- [ ] https://github.com/dbt-labs/dbt/issues/3885
- [ ] https://github.com/dbt-labs/dbt/issues/2330#issuecomment-919798130

**Comment by leahwicz** [comment]
Broke this out from the over-arching story: https://github.com/dbt-labs/dbt/issues/3502

**Comment by jtcohen6** [comment]
I added one more pre-req above, based on the comments I'd left in #3502.

My current feelings about these pre-reqs:
- I believe we can and should resolve #3810
- I could go any way on env vars. @gshank I'd appreciate your take on the relative complexity of those options.
- I'm leaning toward documenting #2330 as a known limitation / unsupported use of `invocation_id` + `run_started_at`

There's one more thing I'd like to do around logging when we turn on partial parsing by default: #3886
