### ISSUE TITLE
Enable deprecation: models-key-mismatch

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt#3899]
### models-key-mismatch

Introduced in: v0.16
In the last week, raised by: 34 projects (<1%)

This is a tricky one: We actually removed this deprecation _warning_ in v0.20, when we removed the `patch_nodes` method. But the to-be-deprecated functionality is still supported.

https://github.com/dbt-labs/dbt/blob/745ae3e64ac03fedb19228b31252fea05eb0ed37/core/dbt/contracts/graph/manifest.py#L685-L691

I'd like to re-add the conditional check for whether a non-model (a seed, snapshot, etc) is specified under the `models:` key, and start raising a clear exception for this in v1.0. This may require some work with @gshank to find where this logic has moved in v0.20+.

Once done, we can also remove this from the list of active deprecations, since it's no longer referenced anywhere in the code!

_Originally posted by @jtcohen6 in https://github.com/dbt-labs/dbt/issues/2798#issuecomment-919998174_

**Comment by emmyoop** [comment]
@gshank can you help point me to where this logic moved to in v0.20+?

**Comment by jtcohen6** [comment]
@emmyoop Some details and a quick reproduction case, based on what we discussed earlier:

Create a seed, `seeds/my_seed.csv`:
```csv
id
1
```
Then define properties for it under a `models` block:
```
# models/whatever.yml
version: 2
models:
  - name: my_seed
    description: "This is my very cool seed"
```

In previous versions of dbt (e.g. v0.19), we raised a deprecation warning for this:
```
* Deprecation Warning: "my_seed" is a seed node, but it is specified in the
models section of models/schema.yml.

To fix this warning, place the `my_seed` specification under the seeds key
instead.
This warning will become an error in a future release.
```
For backwards compatibility, though, we'd still apply the description to `my_seed`.

As of v0.20, we _removed_ the deprecation warning, but continued with the previous backwards-compatible functionality, by applying the description to the seed. In effect, we un-deprecated the feature.
```
dbt --no-partial-parse ls -s my_seed --output json --output-keys description
{"description": "This is my very cool seed"}
```

In v1.0, I'd like to:
- stop applying the properties to resources of the wrong type (i.e. ignore `my_seed` under `models`)
- raise a warning that we found a resource by that name, of the wrong type, and to please move it under the right key instead
