### ISSUE TITLE
Infinite recursion when checking for modified upstream macro

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3904]
Using v0.21.0b2, the [recursive logic](https://github.com/dbt-labs/dbt/blob/d3826e670f0dbe096a7b60189dd20121805572e2/core/dbt/graph/selector_methods.py#L408-L424) that checks for upstream macro modifications in `state:modified` can encounter an infinite recursion:

```
  File "/usr/local/lib/python3.8/dist-packages/dbt/graph/selector_methods.py", line 428, in check_modified
    upstream_macro_change = self.recursively_check_macros_modified(new)
  File "/usr/local/lib/python3.8/dist-packages/dbt/graph/selector_methods.py", line 421, in recursively_check_macros_modified
    return self.recursively_check_macros_modified(macro)
  File "/usr/local/lib/python3.8/dist-packages/dbt/graph/selector_methods.py", line 421, in recursively_check_macros_modified
    return self.recursively_check_macros_modified(macro)
  File "/usr/local/lib/python3.8/dist-packages/dbt/graph/selector_methods.py", line 421, in recursively_check_macros_modified
    return self.recursively_check_macros_modified(macro)
  [Previous line repeated 954 more times]
  File "/usr/local/lib/python3.8/dist-packages/dbt/graph/selector_methods.py", line 420, in recursively_check_macros_modified
    if len(macro.depends_on.macros) > 0:
RecursionError: maximum recursion depth exceeded while calling a Python object
```

We haven't been able to identify the root cause. I see at least one way that this logic can be improved, by skipping over the loop if no macros have been modified:
```python
def recursively_check_macros_modified(self, node):
        # check if there are any changes to any macros the first time
        if self.modified_macros is None:
            self.modified_macros = self._macros_modified()
        
        # no macros have been modified, skip looping
        if not self.modified_macros:
            return False

        # loop through all macros that this node depends on
        for macro_uid in node.depends_on.macros:
            # is this macro one of the modified macros?
            if macro_uid in self.modified_macros:
                return True
            # if not, and this macro depends on other macros, keep looping
            macro = self.manifest.macros[macro_uid]
            if len(macro.depends_on.macros) > 0:
                return self.recursively_check_macros_modified(macro)
            else:
                return False
        return False
```

I'd appreciate guidance from the Core team on what other conditions might cause this logic to loop infinitely. I've tried a macro that calls itself; this does raise a recursion error, but in a different part of the codebase: [`dbt.clients.jinja.track_call`](https://github.com/dbt-labs/dbt/blob/d3826e670f0dbe096a7b60189dd20121805572e2/core/dbt/clients/jinja.py#L314).

**Comment by gshank** [comment]
There are loops in the depends_on macros. Both the 'recursively_get_depends_on_macros' in core/dbt/context/macro_resolver.py and in 'recursively_gather_macro_references' in core/dbt/parser/partial.py skip the loops by checking whether the macro unique_id has already been encountered. Although you don't need to create a list of macro unique_ids for other purposes, you probably need to create one to check to avoid the loops.
