### ISSUE TITLE
Locate failing test data

### ISSUE THREAD

**Issue by pixie79** [dbt-labs/dbt#3919]
If you have a test that fails, I can easily see which test fails and also which table causes the issue.

However, I am not sure how I tell which row or rows have data that failed. Is there a way to log this?

Thanks

**Comment by pixie79** [comment]
It's ok I have found it. The failing query gets put into the log directory for us to then run the manually and locate the error.

That is perfect, just did not understand that from the docs.

**Comment by jtcohen6** [comment]
Correct! The test SQL shows up in the `logs`, as well as in the `target/compiled` folder.

In v0.20, we introduced a new feature that allows you to store test failures in a database table, for quicker debugging in development: https://docs.getdbt.com/docs/building-a-dbt-project/tests#storing-test-failures
