### ISSUE TITLE
Column does not exist in temp table during incremental model run

### ISSUE THREAD

**Issue by jaapdelaat** [dbt-labs/dbt#3938]
First-off, I'd like to state that dbt is an amazing product!

### Describe the bug
An incremental dbt model updates a target table on Redshift, the execution is done by a Gitlab runner using the CICD pipeline functionality.

We needed to add a column to the target table in prod, for sake of simplicity this was done by changing the model in a local repo and executing the following command locally: `dbt run --profiles-dir . --target prod --models INCREMENTAL_MODEL --full-refresh `

This results in an updated target table with the added column on Redshift.

The change in model code was pushed to the Gitlab master repo, assuming the CICD prod Gitlab pipeline would pick-up the added column on Redshift automatically and run without errors. That was not the case, the next run the following error was returned:

`Database Error in model INCREMENTAL_MODEL (models/stage/INCREMENTAL_MODEL.sql)
  column "ADDED_COLUMN" does not exist in INCREMENTAL_MODEL__dbt_tmp040654710781`

Note that `INCREMENTAL_MODEL` and `ADDED_COLUMN` are replacing the actual model and column in question.
Re-running the pipeline does not solve the issue, however a new `INCREMENTAL_MODEL__dbt_tmp` table is created.

**Work-around**
The issue was solved by changing the CICD pipeline temporarily. Running the `INCREMENTAL_MODEL` with the following command:  `dbt run --profiles-dir . --target prod --models `INCREMENTAL_MODEL` --full-refresh `
on the Gitlab CICD pipeline solves the issue.

This is not ideal, as it would mean that for each added column on an incremental model, the CICD pipeline would need a temporary change. I'd expect that this workflow of adding a column manually through executing code locally would work, as the column is actually added to the table in Redshift. That is why I think this is a bug.

### Steps To Reproduce
- Create an incremental model and load a subset of columns and their data onto Redshift
- Configure a Gitlab CICD pipeline that runs this model
- Add a column to the model on a local repo
- Execute a dbt run with a --full-refresh argument for this model
- Check if the column was added to the target table on Redshift
- Push the change in the local repo to the Gitlab repo
- Run the CICD pipeline

### Expected behavior
A Database Error stating that the added column does not exist in a temporary table created by dbt

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [X] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.0
latest version: 0.20.2
Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation
Plugins:
  - snowflake: 0.19.0
  - postgres: 0.19.0
  - redshift: 0.19.0
  - bigquery: 0.19.0

```

**The operating system you're using:**

CICD: Gitlab Kubernetes / Linux
Local: Mac OS Big Sur 11.6

**The output of `python --version`:**
Python 3.8.12

**Comment by jtcohen6** [comment]
@jaapdelaat Thanks for the really detailed write-up!

It sounds like there are two undesirable things happening here. I have good news about the first one, and some confusion about the other.

1. When you edit the definition of an incremental model and add/remove/change columns, it's been necessary to manually add/remove/change columns in the prod version of that incremental model before pushing and running your new code. That's been a functional limitation of incremental models _forever_, and a serious annoyance. In v0.21, no more! We'll be introducing an `on_schema_change` config that can optionally handle column additions, deletions, and type changes. I'd encourage you to read the [prerelease docs](https://next.docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#what-if-the-columns-of-my-incremental-model-change), and to try it out in `v0.21.0-rc1`.

2. That being said: It sounds like you performed the correct manual intervention, and yet the production run was not successful. As far as I can tell, so long as the prod version of `INCREMENTAL_MODEL` in Redshift contained `ADDED_COLUMN`, the only reason why `INCREMENTAL_MODEL__dbt_tmp` _wouldn't_ contain that column is if your production pipeline wasn't running the latest version of your code. The `__dbt_tmp` temp table is created as the exact result of your model SQL during incremental runs, no more and no less:
https://github.com/dbt-labs/dbt/blob/f4f5d319592f71924d3616acea247f1eee59fd9a/core/dbt/include/global_project/macros/materializations/incremental/incremental.sql#L52

Can you confirm that you pushed your code change to the main branch of your Gitlab repo, the one that's deployed in production? I'm wondering if you pushed your change to a different branch, made the manual change to the production version of the table, then re-triggered a pipeline that pulled from the main branch—i.e. not your latest code. That's the only way I can make sense of what happened here.

**Comment by jaapdelaat** [comment]
@jtcohen6 
Thanks for the detailed response, you were absolutely on-point. The code had not been pushed to prod and only to develop!
The on_schema_change feature will come in handy.

Thanks again.

**Comment by jtcohen6** [comment]
Glad we got to the bottom of it! I'm going to close this issue :)
