### ISSUE TITLE
IDE displaying empty strings as NULL 

### ISSUE THREAD

**Issue by andreweduncan** [dbt-labs/dbt#3950]
### Describe the bug
Seems related to Closed PR https://github.com/dbt-labs/dbt/issues/2666.
When testing for NON-NULL values, DBT will return and display empty strings as NULL to the end user.

### Steps To Reproduce

Create a table with two columns: 
1. A STRING column holding a list of short strings (My example strings are either 5 characters long or zero characters long)
and 
2. second column to count the length of a string in the first column (used only for demonstration)

Run the following two queries:

Get all NULL rows from test strings 
<img width="404" alt="Screen Shot 2021-09-24 at 2 53 10 PM" src="https://user-images.githubusercontent.com/72758464/134727314-4bca0225-8ec2-47d2-a5f4-bcbd925b7432.png">
Result: No NULL strings, as expected.

Get non-null string rows shorter than 5 characters
<img width="531" alt="Screen Shot 2021-09-24 at 3 00 55 PM" src="https://user-images.githubusercontent.com/72758464/134727865-d168a5d5-c0d1-4d79-9bb2-7f4c4bfa5c1b.png">
Result: returns seven non-null rows, displays them as NULL

### Expected behavior
Since it correctly tests empty strings as not null, I would expect it to display an empty cell instead of calling 
it "null".

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
using dbt Cloud v1.1.35.48:
```

**The operating system you're using:**
Big Sur 11.6

**The output of `python --version`:**

**Comment by jtcohen6** [comment]
@andreweduncan Good news! This was resolved by #3499 (see https://github.com/dbt-labs/dbt/pull/3499#discussion_r660164490 in particular). We've included that fix in v0.21, which is currently in prerelease. You can try yourself by switching your dbt Cloud development environment to use dbt Core v0.21.0-rc1.
