### ISSUE TITLE
Row 0 has 23 values, but Table only has 22 columns.

### ISSUE THREAD

**Issue by ninomllr** [dbt-labs/dbt#3954]
### Describe the bug
I wanted to test the seeder function but it seems as there is a bug with recognizing the real numbers of columns in CSV files. 

### Steps To Reproduce
- Download the following open dataset: https://data.bs.ch/explore/dataset/100077/download/?format=csv&timezone=Europe/Zurich&lang=en&use_labels_for_header=true&csv_separator=,
- Copy it into the data folder 
- Run `dbt seed`

### Expected behavior
The data gets imported

### Screenshots and log output
```
Running with dbt=0.20.2
Found 2 models, 4 tests, 0 snapshots, 0 analyses, 147 macros, 0 operations, 1 seed file, 0 sources, 0 exposures

17:52:30 | Concurrency: 1 threads (target='dev')
17:52:30 | 
17:52:30 | 1 of 1 START seed file dev.covid19_switzerland....................... [RUN]
17:52:30 | 1 of 1 ERROR loading seed file dev.covid19_switzerland............... [ERROR in 0.92s]
17:52:31 | 
17:52:31 | Finished running 1 seed in 0.98s.

Completed with 1 error and 0 warnings:

Compilation Error in seed covid19_switzerland (data/covid19_switzerland.csv)
  Row 0 has 23 values, but Table only has 22 columns.
  
  > in macro materialization_seed_default (macros/materializations/seed/seed.sql)
  > called by seed covid19_switzerland (data/covid19_switzerland.csv)

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### System information
postgres

**The output of `dbt --version`:**
```
installed version: 0.20.2
   latest version: 0.20.2

Up to date!

Plugins:
  - redshift: 0.20.2
  - postgres: 0.20.2
  - bigquery: 0.20.2```

**The operating system you're using:**
Ubuntu

**The output of `python --version`:**
Python 3.8.10

**Comment by jtcohen6** [comment]
@ninomllr Works just fine for me!
```
$ dbt seed --full-refresh
Running with dbt=0.20.2
Found 2 models, 7 tests, 0 snapshots, 0 analyses, 147 macros, 0 operations, 1 seed file, 1 source, 0 exposures

19:32:53 | Concurrency: 5 threads (target='dev')
19:32:53 |
19:32:53 | 1 of 1 START seed file dbt_jcohen.100077............................. [RUN]
19:32:57 | 1 of 1 OK loaded seed file dbt_jcohen.100077......................... [CREATE 13797 in 3.09s]
19:32:57 |
19:32:57 | Finished running 1 seed in 3.21s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```
Note that, since the column headers contain spaces, I set this config in my project file:
```yml
# dbt_project.yml
seeds:
  quote_columns: True
```

There are indeed 22 columns in the table. The specific error message you've included (`Row 0 has 23 values, but Table only has 22 columns`) seems to indicate that one of the values in the first row contains an extra comma, without quotes to wrap the value. But I haven't been able to reproduce the error locally.

**Comment by ninomllr** [comment]
Thanks for trying it out. I quickly tried the addition in the dbt_projects.yml file, as well as with the `--full-refresh` parameter and it didn't help yet. I found the same issue here in a project using `csvlook`. Is dbt using the same base? https://github.com/wireservice/csvkit/issues/751

**Comment by ninomllr** [comment]
Ok I redownloaded the file again and now it works... Maybe I messed something up yesterday when storing the file? Anyway, thanks for the help, it was probably my fault. :-)
