### ISSUE TITLE
Externalise db connections (airflow)

### ISSUE THREAD

**Issue by pixie79** [dbt-labs/dbt#3965]
Hi

From a security and automation point of view it would be great if you could pass a connection  string as part of the dbt run commands instead of them having to be setup in advance in profiles.yml.

This would then hopefully allow for example connections setup in airflow to be passed on for use in DBT. This would be a real boast for environments with multiple uses and where aws managed apache airflow is used.

As a first step is there the option for loading the connections from a seperate yml file for example connections.yml? That would allow for a hacky airflow pipeline to write that file first as an earlier part of the job run.

  
Thanks

Mark

**Comment by jtcohen6** [comment]
@pixie79 I agree! We're actually thinking right now about better ways to pass connection profile information into dbt-core, and how we might get away from the hard requirement for a specific local file named `profiles.yml`.

That said, for the time being, it's totally possible to:
1. Point to a different directory using the `--profiles-dir` flag (though the file must be named `profiles.yml`, unfortunately)
2. Access all profile keys (under `outputs`) via the `{{ env_var() }}` function, allowing you to pass in all profile information via env vars

I'm hopeful that's enough to go on for passing profile information from Airflow, either by having it write and point to the file into a relative path before kicking off dbt (1) or by having it pass in all the requisite information via env vars (2).

There may be more to come on this, and it will likely be in the form of new issues with more-specific proposals. I'm going to close this issue in the meantime.
